/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Annelida (https://sketchfab.com/Annelida)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-robot-domowik-8f1f61ca0c844b978abfb43243513377
Title: Toy robot Domowik
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Astronaut(props) {
  const group = useRef();
  const { scene, animations } = useGLTF(`${import.meta.env.BASE_URL}models/toy_robot_domowik.glb`);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = animations.length > 0 ? actions[animations[0].name] : null;
    action?.reset().play();
    return () => action?.stop();
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/toy_robot_domowik.glb`);
